apiVersion: v1
kind: Namespace
metadata:
  name: simplenode-dev
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
    keptn.sh/lifecycle-controller: "enabled"  # this lines tells the webhook to handle the namespace
